/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tokenizedBallotSol from "./TokenizedBallot.sol";
export { MyERC20Votes__factory } from "./MyERC20Votes__factory";
